/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FilterNode : TBase
{
  private int _viewTreeDepth;
  private long _nodeSourceId;

  public int ViewTreeDepth
  {
    get
    {
      return _viewTreeDepth;
    }
    set
    {
      __isset.viewTreeDepth = true;
      this._viewTreeDepth = value;
    }
  }

  public long NodeSourceId
  {
    get
    {
      return _nodeSourceId;
    }
    set
    {
      __isset.nodeSourceId = true;
      this._nodeSourceId = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool viewTreeDepth;
    public bool nodeSourceId;
  }

  public FilterNode() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ViewTreeDepth = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              NodeSourceId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("FilterNode");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.viewTreeDepth) {
        field.Name = "viewTreeDepth";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ViewTreeDepth);
        oprot.WriteFieldEnd();
      }
      if (__isset.nodeSourceId) {
        field.Name = "nodeSourceId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(NodeSourceId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FilterNode(");
    bool __first = true;
    if (__isset.viewTreeDepth) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ViewTreeDepth: ");
      __sb.Append(ViewTreeDepth);
    }
    if (__isset.nodeSourceId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("NodeSourceId: ");
      __sb.Append(NodeSourceId);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

