/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum GestureEventType
{
  NONE = 0,
  GESTURE_CLICK = 9,
  GESTURE_DOUBLE_CLICK = 10,
  GESTURE_LONG_CLICK = 11,
}
