/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum InputEventType
{
  KEY_CODE_1 = 0,
  KEY_CODE_2 = 1,
  KEY_CODE_3 = 2,
  KEY_CODE_4 = 3,
  KEY_CODE_5 = 4,
  KEY_CODE_6 = 5,
  KEY_CODE_7 = 6,
  KEY_CODE_8 = 7,
  KEY_CODE_9 = 8,
  KEY_CODE_VOICE_UP = 9,
  KEY_CODE_VOICE_DOWN = 10,
}
