/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum NodeEventType
{
  NONE = 0,
  FOCUS = 1,
  CLICK = 2,
  DOUBLE_CLICK = 3,
  LONG_CLICK = 4,
  SCROOL_FORWARD = 5,
  SCROOL_BACKDOWD = 6,
  FIND_NODE = 7,
  EXISTS_NODE = 8,
  SET_TEXT = 12,
  GET_TEXT = 13,
  GET_DESCRIPTION = 14,
}
