/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum NodeResultType
{
  OK = 0,
  FAIL = 1,
  NOEXIST = 2,
  NOCLICK = 3,
  NOLONGCLICK = 4,
  NOEDIT = 5,
  NOSCROLL = 6,
  NOAPPFORWARD = 7,
  NOAPP = 8,
  MORENODE = 9,
}
