/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum PointEventType
{
  NONE = 0,
  CLICK_POINT = 9,
  DOUBLE_CLICK_POINT = 10,
  LONG_CLICK_POINT = 11,
}
