/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ScrapResponse : TBase
{
  private int _rtn;
  private Selector _selector;
  private int _id;

  public int Rtn
  {
    get
    {
      return _rtn;
    }
    set
    {
      __isset.rtn = true;
      this._rtn = value;
    }
  }

  public Selector Selector
  {
    get
    {
      return _selector;
    }
    set
    {
      __isset.selector = true;
      this._selector = value;
    }
  }

  public int Id
  {
    get
    {
      return _id;
    }
    set
    {
      __isset.id = true;
      this._id = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool rtn;
    public bool selector;
    public bool id;
  }

  public ScrapResponse() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Rtn = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Selector = new Selector();
              Selector.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ScrapResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.rtn) {
        field.Name = "rtn";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Rtn);
        oprot.WriteFieldEnd();
      }
      if (Selector != null && __isset.selector) {
        field.Name = "selector";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Selector.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.id) {
        field.Name = "id";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Id);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ScrapResponse(");
    bool __first = true;
    if (__isset.rtn) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Rtn: ");
      __sb.Append(Rtn);
    }
    if (Selector != null && __isset.selector) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Selector: ");
      __sb.Append(Selector== null ? "<null>" : Selector.ToString());
    }
    if (__isset.id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Id: ");
      __sb.Append(Id);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

