/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ScreenPosition : TBase
{
  private Point _coordinate;
  private double _dpi;
  private int _resolutionWidth;
  private int _resolutionHeight;

  public Point Coordinate
  {
    get
    {
      return _coordinate;
    }
    set
    {
      __isset.coordinate = true;
      this._coordinate = value;
    }
  }

  public double Dpi
  {
    get
    {
      return _dpi;
    }
    set
    {
      __isset.dpi = true;
      this._dpi = value;
    }
  }

  public int ResolutionWidth
  {
    get
    {
      return _resolutionWidth;
    }
    set
    {
      __isset.resolutionWidth = true;
      this._resolutionWidth = value;
    }
  }

  public int ResolutionHeight
  {
    get
    {
      return _resolutionHeight;
    }
    set
    {
      __isset.resolutionHeight = true;
      this._resolutionHeight = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool coordinate;
    public bool dpi;
    public bool resolutionWidth;
    public bool resolutionHeight;
  }

  public ScreenPosition() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Coordinate = new Point();
              Coordinate.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Dpi = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              ResolutionWidth = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              ResolutionHeight = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ScreenPosition");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Coordinate != null && __isset.coordinate) {
        field.Name = "coordinate";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Coordinate.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.dpi) {
        field.Name = "dpi";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Dpi);
        oprot.WriteFieldEnd();
      }
      if (__isset.resolutionWidth) {
        field.Name = "resolutionWidth";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ResolutionWidth);
        oprot.WriteFieldEnd();
      }
      if (__isset.resolutionHeight) {
        field.Name = "resolutionHeight";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ResolutionHeight);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ScreenPosition(");
    bool __first = true;
    if (Coordinate != null && __isset.coordinate) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Coordinate: ");
      __sb.Append(Coordinate== null ? "<null>" : Coordinate.ToString());
    }
    if (__isset.dpi) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Dpi: ");
      __sb.Append(Dpi);
    }
    if (__isset.resolutionWidth) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ResolutionWidth: ");
      __sb.Append(ResolutionWidth);
    }
    if (__isset.resolutionHeight) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ResolutionHeight: ");
      __sb.Append(ResolutionHeight);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

