/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum SystemEventType
{
  START_APP_FOR_PACKAGE = 0,
  START_APP_FOR_ACTIVITY = 1,
  START_APP_GET_RUNNING_ACTIVITY = 2,
  START_APP_GET_PACKAGE = 3,
}
